[build]
  base = "."
  command = "npm run build"
  publish = "build"

[[redirects]]
  from = "/old-path"
  to = "/new-path"
  status = 301

# Fallback rule for single-page applications
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/build/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
